on:
  release:
    types: [published]

env:
  # renovate: depName=rust-lang/rust
  RUST_VERSION: 1.74.1
  # renovate: datasource=docker depName=ghcr.io/renovatebot/base-image versioning=docker
  SLIM_IMAGE_VERSION: "1.14.7"
  # renovate: datasource=docker depName=ghcr.io/renovatebot/base-image versioning=docker
  FULL_IMAGE_VERSION: 1.14.7-full

jobs:
  push_to_registry:
    name: Push Docker image to Github Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Branch name
        id: branch_name
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
      - name: Log in to Github Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/rust-musl-builder:${{ env.RUST_VERSION }}-llvm-cov
          build-args: |
            TOOLCHAIN=${{ env.RUST_VERSION }}
